rem gcc -c dummy.c -o build_sdl/dummy.o
rem gcc -c am_map.c -o build_sdl/am_map.o
rem gcc -c doomdef.c -o build_sdl/doomdef.o
rem gcc -c doomstat.c -o build_sdl/doomstat.o
rem gcc -c dstrings.c -o build_sdl/dstrings.o
rem gcc -c d_event.c -o build_sdl/d_event.o
rem gcc -c d_items.c -o build_sdl/d_items.o
rem gcc -c d_iwad.c -o build_sdl/d_iwad.o
rem gcc -c d_loop.c -o build_sdl/d_loop.o
rem gcc -c d_main.c -o build_sdl/d_main.o
rem gcc -c d_mode.c -o build_sdl/d_mode.o
rem gcc -c d_net.c -o build_sdl/d_net.o
rem gcc -c f_finale.c -o build_sdl/f_finale.o
rem gcc -c f_wipe.c -o build_sdl/f_wipe.o
rem gcc -c g_game.c -o build_sdl/g_game.o
rem gcc -c hu_lib.c -o build_sdl/hu_lib.o
rem gcc -c hu_stuff.c -o build_sdl/hu_stuff.o
rem gcc -c info.c -o build_sdl/info.o
rem gcc -c i_cdmus.c -o build_sdl/i_cdmus.o
rem gcc -c i_endoom.c -o build_sdl/i_endoom.o
rem gcc -c i_joystick.c -o build_sdl/i_joystick.o
rem gcc -c i_scale.c -o build_sdl/i_scale.o
rem gcc -c i_sound.c -o build_sdl/i_sound.o
rem gcc -c i_system.c -o build_sdl/i_system.o
rem gcc -c i_timer.c -o build_sdl/i_timer.o
rem gcc -c memio.c -o build_sdl/memio.o
rem gcc -c m_argv.c -o build_sdl/m_argv.o
rem gcc -c m_bbox.c -o build_sdl/m_bbox.o
rem gcc -c m_cheat.c -o build_sdl/m_cheat.o
rem gcc -c m_config.c -o build_sdl/m_config.o
rem gcc -c m_controls.c -o build_sdl/m_controls.o
rem gcc -c m_fixed.c -o build_sdl/m_fixed.o
rem gcc -c m_menu.c -o build_sdl/m_menu.o
rem gcc -c m_misc.c -o build_sdl/m_misc.o
rem gcc -c m_random.c -o build_sdl/m_random.o
rem gcc -c p_ceilng.c -o build_sdl/p_ceilng.o
rem gcc -c p_doors.c -o build_sdl/p_doors.o
rem gcc -c p_enemy.c -o build_sdl/p_enemy.o
rem gcc -c p_floor.c -o build_sdl/p_floor.o
rem gcc -c p_inter.c -o build_sdl/p_inter.o
rem gcc -c p_lights.c -o build_sdl/p_lights.o
rem gcc -c p_map.c -o build_sdl/p_map.o
rem gcc -c p_maputl.c -o build_sdl/p_maputl.o
rem gcc -c p_mobj.c -o build_sdl/p_mobj.o
rem gcc -c p_plats.c -o build_sdl/p_plats.o
rem gcc -c p_pspr.c -o build_sdl/p_pspr.o
rem gcc -c p_saveg.c -o build_sdl/p_saveg.o
rem gcc -c p_setup.c -o build_sdl/p_setup.o
rem gcc -c p_sight.c -o build_sdl/p_sight.o
rem gcc -c p_spec.c -o build_sdl/p_spec.o
rem gcc -c p_switch.c -o build_sdl/p_switch.o
rem gcc -c p_telept.c -o build_sdl/p_telept.o
rem gcc -c p_tick.c -o build_sdl/p_tick.o
rem gcc -c p_user.c -o build_sdl/p_user.o
rem gcc -c r_bsp.c -o build_sdl/r_bsp.o
rem gcc -c r_data.c -o build_sdl/r_data.o
rem gcc -c r_draw.c -o build_sdl/r_draw.o
rem gcc -c r_main.c -o build_sdl/r_main.o
rem gcc -c r_plane.c -o build_sdl/r_plane.o
rem gcc -c r_segs.c -o build_sdl/r_segs.o
rem gcc -c r_sky.c -o build_sdl/r_sky.o
rem gcc -c r_things.c -o build_sdl/r_things.o
rem gcc -c sha1.c -o build_sdl/sha1.o
rem gcc -c sounds.c -o build_sdl/sounds.o
rem gcc -c statdump.c -o build_sdl/statdump.o
rem gcc -c st_lib.c -o build_sdl/st_lib.o
rem gcc -c st_stuff.c -o build_sdl/st_stuff.o
rem gcc -c s_sound.c -o build_sdl/s_sound.o
rem gcc -c tables.c -o build_sdl/tables.o
rem gcc -c v_video.c -o build_sdl/v_video.o
rem gcc -c wi_stuff.c -o build_sdl/wi_stuff.o
rem gcc -c w_checksum.c -o build_sdl/w_checksum.o
rem gcc -c w_file.c -o build_sdl/w_file.o
rem gcc -c w_main.c -o build_sdl/w_main.o
rem gcc -c w_wad.c -o build_sdl/w_wad.o
rem gcc -c z_zone.c -o build_sdl/z_zone.o
rem gcc -c w_file_stdc.c -o build_sdl/w_file_stdc.o
rem gcc -c i_input.c -o build_sdl/i_input.o
gcc -c i_video.c -o build_sdl/i_video.o
rem gcc -c doomgeneric.c -o build_sdl/doomgeneric.o

gcc -c doomgeneric_sdl.c -o build_sdl/doomgeneric_sdl.o
gcc build_sdl/*.o -o doom.exe -lmingw32 -lsdl2main -lsdl2